/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author professor
 */
public class Solicitacoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Solicitacoes
     */
    public Solicitacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSolicitacoesTabela = new javax.swing.JTable();
        jButtonSolicitacoesVisualizar = new javax.swing.JButton();
        jButtonSolicitacoesVoltar = new javax.swing.JButton();
        jButtonSolicitacoesAlterar = new javax.swing.JButton();
        jButtonSolicitacoesExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Solicitações");
        setPreferredSize(new java.awt.Dimension(467, 297));

        jTableSolicitacoesTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableSolicitacoesTabela);

        jButtonSolicitacoesVisualizar.setText("Editar");

        jButtonSolicitacoesVoltar.setText("Voltar");
        jButtonSolicitacoesVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolicitacoesVoltarActionPerformed(evt);
            }
        });

        jButtonSolicitacoesAlterar.setText("Aceitar");

        jButtonSolicitacoesExcluir.setText("Recusar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSolicitacoesVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSolicitacoesExcluir)
                                .addGap(36, 36, 36)
                                .addComponent(jButtonSolicitacoesVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(jButtonSolicitacoesAlterar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSolicitacoesVisualizar)
                    .addComponent(jButtonSolicitacoesAlterar)
                    .addComponent(jButtonSolicitacoesExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButtonSolicitacoesVoltar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        setBounds(0, 0, 467, 293);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSolicitacoesVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitacoesVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSolicitacoesVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSolicitacoesAlterar;
    private javax.swing.JButton jButtonSolicitacoesExcluir;
    private javax.swing.JButton jButtonSolicitacoesVisualizar;
    private javax.swing.JButton jButtonSolicitacoesVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSolicitacoesTabela;
    // End of variables declaration//GEN-END:variables
}
