/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modelo.ModeloUsuario;

/**
 *
 * @author professor
 */
public class TelaMeuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaMeuUsuario
     */
    boolean botaoUsuario = false;
    boolean botaoSenha = false;
    public TelaMeuUsuario() {
        initComponents();   
        jTextFieldMeuUsuarioUsuario.setEditable(false);
        jPasswordFieldMeuUsuarioConfirmarSenha.setEditable(false);
        jPasswordFieldMeuUsuarioSenha.setEditable(false);
        botaoUsuario = false;
        botaoSenha = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMeuUsuarioUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAlterarLoginMeuUsuario = new javax.swing.JButton();
        jButtonAlterarSenhaMeuUsuario = new javax.swing.JButton();
        jButtonSalvarAlteracoesMeuUsuario = new javax.swing.JButton();
        jPasswordFieldMeuUsuarioSenha = new javax.swing.JPasswordField();
        jPasswordFieldMeuUsuarioConfirmarSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Meu usuário");

        jLabel1.setText("Usuário");

        jLabel3.setText("Senha");

        jLabel4.setText("Confirmar");

        jButtonAlterarLoginMeuUsuario.setText("Alterar login");
        jButtonAlterarLoginMeuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarLoginMeuUsuarioActionPerformed(evt);
            }
        });

        jButtonAlterarSenhaMeuUsuario.setText("Alterar senha");
        jButtonAlterarSenhaMeuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarSenhaMeuUsuarioActionPerformed(evt);
            }
        });

        jButtonSalvarAlteracoesMeuUsuario.setText("Salvar alterações");
        jButtonSalvarAlteracoesMeuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarAlteracoesMeuUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldMeuUsuarioUsuario)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jPasswordFieldMeuUsuarioSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldMeuUsuarioConfirmarSenha))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAlterarSenhaMeuUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAlterarLoginMeuUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSalvarAlteracoesMeuUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMeuUsuarioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterarLoginMeuUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterarSenhaMeuUsuario)
                    .addComponent(jPasswordFieldMeuUsuarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarAlteracoesMeuUsuario)
                    .addComponent(jPasswordFieldMeuUsuarioConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(320, 264));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarLoginMeuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarLoginMeuUsuarioActionPerformed
        jTextFieldMeuUsuarioUsuario.setEditable(true);
        if(!botaoUsuario){        
        jButtonAlterarLoginMeuUsuario.setText("Manter login");
        jTextFieldMeuUsuarioUsuario.requestFocus();
        botaoUsuario = true;
        }else{
            jButtonAlterarLoginMeuUsuario.setText("Alterar login");
            jTextFieldMeuUsuarioUsuario.setEditable(false);
            botaoUsuario = false;
        }
    }//GEN-LAST:event_jButtonAlterarLoginMeuUsuarioActionPerformed

    private void jButtonAlterarSenhaMeuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarSenhaMeuUsuarioActionPerformed
        jPasswordFieldMeuUsuarioSenha.setEditable(true);
        jPasswordFieldMeuUsuarioConfirmarSenha.setEditable(true);
        if(!botaoSenha){        
        jButtonAlterarSenhaMeuUsuario.setText("Manter senha");
        jPasswordFieldMeuUsuarioConfirmarSenha.requestFocus();
        jPasswordFieldMeuUsuarioSenha.requestFocus();
        botaoSenha = true;
        }else{
            jButtonAlterarSenhaMeuUsuario.setText("Alterar senha");
            jPasswordFieldMeuUsuarioConfirmarSenha.setEditable(false);
            jPasswordFieldMeuUsuarioSenha.setEditable(false);
            botaoSenha = false;
        }
    }//GEN-LAST:event_jButtonAlterarSenhaMeuUsuarioActionPerformed

    private void jButtonSalvarAlteracoesMeuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarAlteracoesMeuUsuarioActionPerformed
        String campoUsuario = jTextFieldMeuUsuarioUsuario.getText();
        String campoSenha = jPasswordFieldMeuUsuarioSenha.getText();
        String campoConfirmaSenha = jPasswordFieldMeuUsuarioConfirmarSenha.getText();
        ModeloUsuario model = new ModeloUsuario();
        if((campoUsuario.length() <= 15) && verificaCaracteres(campoUsuario)){
            if ((campoSenha.length() >= 4) && (campoSenha.length() <= 8) && (verificaCaracteres(campoSenha)) ){
                if(campoConfirmaSenha.equals(campoSenha)){                                        
                        switch(JOptionPane.showConfirmDialog(null, "Deseja salvar as alterações?")){
                            case 0: 
                                model.setUsuario(campoUsuario);
                                model.setSenha(campoSenha);      
                                jTextFieldMeuUsuarioUsuario.setEnabled(false);
                                jPasswordFieldMeuUsuarioSenha.setEnabled(false);
                                jPasswordFieldMeuUsuarioConfirmarSenha.setEnabled(false);
                                break;
                            case 2:
                                jTextFieldMeuUsuarioUsuario.setText("");
                                jPasswordFieldMeuUsuarioSenha.setText("");
                                jPasswordFieldMeuUsuarioConfirmarSenha.setText("");
                                jTextFieldMeuUsuarioUsuario.setEnabled(false);
                                jPasswordFieldMeuUsuarioSenha.setEnabled(false);
                                jPasswordFieldMeuUsuarioConfirmarSenha.setEnabled(false);
                                break; 
                        }
                }else{
                    JOptionPane.showMessageDialog(null, "Campos de senha diferentes!");
                    jPasswordFieldMeuUsuarioSenha.setText("");
                    jPasswordFieldMeuUsuarioConfirmarSenha.setText("");
                    jPasswordFieldMeuUsuarioSenha.requestFocus();
                }
            }else
                JOptionPane.showMessageDialog(null,"Senha inválida!");
        }else
            JOptionPane.showMessageDialog(null, "Usuário inválido!");           
    }//GEN-LAST:event_jButtonSalvarAlteracoesMeuUsuarioActionPerformed

    public boolean verificaCaracteres(String campo){
        if(campo.matches("[\\da-zA-Z]+"))
            return true;
        else
            return false;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMeuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMeuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMeuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMeuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMeuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarLoginMeuUsuario;
    private javax.swing.JButton jButtonAlterarSenhaMeuUsuario;
    private javax.swing.JButton jButtonSalvarAlteracoesMeuUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldMeuUsuarioConfirmarSenha;
    private javax.swing.JPasswordField jPasswordFieldMeuUsuarioSenha;
    private javax.swing.JTextField jTextFieldMeuUsuarioUsuario;
    // End of variables declaration//GEN-END:variables
}
