/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author professor
 */
public class VisualizarReunioes extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisualizarReunioes
     */
    public VisualizarReunioes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVisualizarReunioesTabela = new javax.swing.JTable();
        jButtonVisualizarReunioesVisualizar = new javax.swing.JButton();
        jButtonVisualizarReunioesVoltar = new javax.swing.JButton();
        jButtonVisualizarReunioesAlterar = new javax.swing.JButton();
        jButtonVisualizarReunioesExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Visualizar Reuniões");
        setPreferredSize(new java.awt.Dimension(467, 297));

        jTableVisualizarReunioesTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableVisualizarReunioesTabela);

        jButtonVisualizarReunioesVisualizar.setText("Visualizar");

        jButtonVisualizarReunioesVoltar.setText("Voltar");
        jButtonVisualizarReunioesVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarReunioesVoltarActionPerformed(evt);
            }
        });

        jButtonVisualizarReunioesAlterar.setText("Alterar");

        jButtonVisualizarReunioesExcluir.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVisualizarReunioesVoltar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVisualizarReunioesExcluir)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonVisualizarReunioesVisualizar)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonVisualizarReunioesAlterar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVisualizarReunioesAlterar)
                    .addComponent(jButtonVisualizarReunioesExcluir)
                    .addComponent(jButtonVisualizarReunioesVisualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVisualizarReunioesVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 467, 293);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVisualizarReunioesVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarReunioesVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVisualizarReunioesVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVisualizarReunioesAlterar;
    private javax.swing.JButton jButtonVisualizarReunioesExcluir;
    private javax.swing.JButton jButtonVisualizarReunioesVisualizar;
    private javax.swing.JButton jButtonVisualizarReunioesVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVisualizarReunioesTabela;
    // End of variables declaration//GEN-END:variables
}
